name: Google Scholar Stats
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (Optional) Run workflow manually
  workflow_dispatch:
  # (Optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}

jobs:
  google-scholar-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }} 
          
          # Options
          user: mariolpantunes
          template: classic
          base: "" # This ensures we only get the plugin content, not the full github stats again
          filename: google-scholar-stats.svg
          
          # Google Scholar Plugin
          plugin_scholar: yes
          plugin_scholar_id: HXq2unUAAAAJ
          plugin_scholar_sections: citations
          plugin_scholar_details: citations, scholar
